---
title: "Data Analyses"
output: html_document
date: "2023-02-12"
---

# Import
```{r, echo=F, message=F}

# install.packages('Rcpp', dependencies = TRUE)
# install.packages("stargazer")

# libraries:
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(reshape)
library(glue)
library(mgcv)
library(nlme)
library(Matrix)
library(lme4)
library(wesanderson)
library(viridis)
library(tidyverse)
library(htmltools)
library(qgam)
library(voxel)
library(lmerTest)
library(mgcViz)
library(stargazer)
library(cowplot)


# install.packages('jtools')
library(jtools)
options(scipen=5, digits = 5)
```

# Prepare the data to analysis 
```{r, message=F, warning=F, error=F}
# Reading the file:
#dir <- "C:/Users/Merav/Documents/GitHub/Statistics-Project/atopic_comorbidities_first_second_year_10.5.23.xlsx"
# dir <- "C:/Users/edena/Documents/GitHub/Statistics-Project/atopic_comorbidities_first_second_year_10.5.23.xlsx"
# dir <- "C:/Users/Shahar/Documents/GitHub/Statistics-Project/atopic_comorbidities_first_second_year_10.5.23.xlsx"
dir <- "C:/Users/shahars/OneDrive - Playtika Ltd/Documents/GitHub/Statistics-Project/atopic_comorbidities_first_second_year_10.5.23.xlsx"

df_raw <- read_excel(dir, sheet = 1)
df <- df_raw %>% mutate(DOB = as.Date(DOB)) 

df <- df %>% filter(is.na(lost_of_followup))# Filtering only participants that completed the survey
df <- df %>% filter(month_survey_complete == 2) # Filtering only participants that completed the second year
df <- df[,-c(51:88)]# Removing non relevant columns: from type_of_allergy to 12_month_FA_type_allergy

not_relevant <- c('allergist_followup', 'last_spt', 'epipen', 'mistake_exposure', 'reaction_type24', 'diagnosis_by', 'lost_of_followup',"mother_no_comorbidities","mother_other","father_no_comorbidities","father_other","sibling1_other","sibling1_no_comorbidities","sibling2_other","sibling2_no_comorbidities","sibling3_other","sibling3_no_comorbidities","sibling4_other","sibling4_no_comorbidities")
df <- df[-which(colnames(df) %in% not_relevant)] # Removing columns with alot on NA:

# Adding binary columns 
df$family_Atopic_diseases_sum <- rowSums(df[,14:37]) # Did any one from family (mother, father, sib) have *any* of the disease?
df$mother_Atopic_diseases_sum <- rowSums(df[,14:17]) # Did a disease appear in a specific family member?
df$father_Atopic_diseases_sum <- rowSums(df[,18:21])
df$sibling_Atopic_diseases_sum <- rowSums(df[,22:37])
              
# Binary variable for each family member 
df <- df %>% mutate(family_Atopic_diseases = ifelse(family_Atopic_diseases_sum >0,1,0),
                    mother_Atopic_diseases = ifelse(mother_Atopic_diseases_sum>0,1,0),
                    father_Atopic_diseases = ifelse(father_Atopic_diseases_sum > 0, 1,0),
                    sibling_Atopic_diseases = ifelse(sibling_Atopic_diseases_sum > 0 ,1, 0))


# Changing to binary variables:
df$gender[df$gender == 2] <- 0
df$`Jew/Arab`[df$`Jew/Arab` == 2] <- 0
df$food_allergy_24_month[df$food_allergy_24_month == 2] <- 0
df$inhalation_24_month[df$inhalation_24_month == 2] <- 0
df$prevention_therapy[df$prevention_therapy == 2] <- 0
df$AD_24_month[df$AD_24_month == 2] <- 0
df$steroids_treatment24[df$steroids_treatment24 == 2] <- 0
df$ABX_treatment_24_months[df$ABX_treatment_24_months == 2] <- 0
df$hospitalization_24_months[df$hospitalization_24_months == 2] <- 0
df$chronic_disease_24[df$chronic_disease_24 == 2] <- 0
df$type_of_pregnancy[df$type_of_pregnancy == 2] <- 0

#Changing NA to 0 for 
df$number_ABX_treatment_24_months<- replace(df$number_ABX_treatment_24_months, is.na(df$number_ABX_treatment_24_months), 0)
df$hospitalization_24_months<- replace(df$hospitalization_24_months, is.na(df$hospitalization_24_months), 0)
df$prevention_therapy<- replace(df$prevention_therapy, is.na(df$prevention_therapy), 0)
df$number_inhalation<- replace(df$number_inhalation, is.na(df$number_inhalation), 0)
df$AD_treatment_24_month<- replace(df$AD_treatment_24_month, is.na(df$AD_treatment_24_month), 0)
df$steroids_treatment24<- replace(df$steroids_treatment24, is.na(df$steroids_treatment24), 0)
df$number_steroid_treat<- replace(df$number_steroid_treat
, is.na(df$number_steroid_treat), 0)
df$number_of_ABX_first_year<- replace(df$number_of_ABX_first_year, is.na(df$number_of_ABX_first_year), 0)

df <- df %>% mutate(SES_group = ifelse(SES>8, '9-10', ifelse(SES>5, '6-8', '1-5')))# create a category SES variable :

#Creating dependent variables with the correct name 
df$FA_second_year <-  df$food_allergy_24_month
df$AD_second_year <- df$AD_24_month
df$HRAD_second_year <- df$inhalation_24_month
df$ABX_second_year <- df$ABX_treatment_24_months
df$feeding_type <- df$study_group_COMEET

#option A of explanatory var:
df <- df %>% mutate(is_atopic_first_year = ifelse((AD_first_year + FA_first_year +  HRAD_first_year)>0,1,0), 
                    is_atopic_second_year = ifelse((AD_second_year + FA_second_year + HRAD_second_year)>0,1,0))

#Choosing explanatory variables: Ones that have a sufficient number of observation before and after Corona
#The distribution of observations according to the timeline of the corona. Before the corona = 1, the first six months of the corona = 2  and after = 3:
group1 <- as.Date("2019-03-01")
group2 <- as.Date("2020-03-11")
group3 <- as.Date("2021-02-07")

g1 <- as.numeric(as.Date("2019-03-01")) - min(as.numeric(as.Date(df$DOB)))
g2 <- as.numeric(as.Date("2020-03-11")) - min(as.numeric(as.Date(df$DOB)))
g3 <- as.numeric(as.Date("2021-02-07")) - min(as.numeric(as.Date(df$DOB)))

df$DOB_count = as.numeric(as.Date(df$DOB)) - min(as.numeric(as.Date(df$DOB)))

df <- df %>% mutate(covid_time = ifelse(DOB < group1, 1, ifelse(DOB < group2, 2, ifelse(DOB<group3, 3, 4))))
df <- df %>% mutate(Born_at = ifelse(covid_time == 1, 'Up to March19', ifelse(covid_time == 2, 'March19 - March20', 'March20 - Feb21')))

# Change categorical variable to factors 
df$feeding_type <- as.factor(df$feeding_type)
df$gender <- as.factor(df$gender)
df$mother_Atopic_diseases <- as.factor(df$mother_Atopic_diseases)
df$father_Atopic_diseases <- as.factor(df$father_Atopic_diseases)
df$mother_education <- as.factor(df$mother_education)
df$type_of_pregnancy <- as.factor(df$type_of_pregnancy)
df$nursing_setup_at_12mo <- as.factor(df$nursing_setup_at_12mo)
df$covid_time <- as.factor(df$covid_time)

## preapre the final data frame for the models 
df_mdl <- df %>% drop_na(SES_group, gender, type_of_pregnancy, mother_education, vaccine_12mo, nursing_setup_at_12mo, is_atopic_first_year, is_atopic_second_year) %>% 
  filter(mother_year_birth >1960, mother_year_birth < 2000) %>% 
  mutate(is_atopic_both = ifelse(is_atopic_first_year >0, ifelse(is_atopic_second_year>0, 1, 0),0), is_atopic_any = ifelse(is_atopic_first_year + is_atopic_second_year >0,1,0))

#reduce variance from this variable
df_mdl$mother_year_birth = df_mdl$mother_year_birth - 1961

attach(df_mdl)
```


# Descriptive statistics :
```{r, fig.width=10, fig.height=3}
n_df = df_mdl %>% group_by(covid_time ) %>% summarise(n = n(), is_atopic_first_year = sum(is_atopic_first_year), is_atopic_second_year = sum(is_atopic_second_year), is_atopic_any = sum(is_atopic_any), is_atopic_both = sum(is_atopic_both)) 

n_df <- n_df %>% mutate(is_atopic_first_year_perc = round(100*is_atopic_first_year/n), 
                        is_atopic_second_year_perc = round(100*is_atopic_second_year/n), 
                        is_atopic_any_perc = round(100*is_atopic_any/n),
                        is_atopic_both_perc = round(100*is_atopic_both/n))

plot_df <- data.frame(covid_time = rep(c(1,2,3,4), 4), 
                      atopic = c(rep('1) First year',4), rep('2) Secound year',4), rep('3) First or Second year',4), rep('4) First and Second',4)) , 
                      precent = c(n_df$is_atopic_first_year_perc, n_df$is_atopic_second_year_perc, n_df$is_atopic_any_perc, n_df$is_atopic_both_perc))

Descriptive_plot <-  ggplot(plot_df, aes(covid_time, y = precent, fill = as.factor(covid_time))) + 
  geom_col() + theme_bw() + facet_wrap(~atopic, nrow=1) + 
  scale_fill_manual(values=c('dodgerblue4', 'darkorange1', 'green4', 'red4'),
                    name = "Born at", labels =c('Up to March19','March19 - March20','March20 - Feb21', 'From Feb21')) + ylim(c(0,100)) +
  xlab("")+  ylab("Atopic disease (%)") + 
  theme(axis.text.x = element_text(color = 'white'), text = element_text(size =12), strip.text = element_text(face = "bold")) + labs(title = 'The percentage of babies with atopic disease') + 
  geom_text(aes(label = round(plot_df$precent,3)), vjust = 0, size = 3.5, fontface = "bold")

# ggsave('Descriptive_plot.jpeg',Descriptive_plot, width =10, height =3)
Descriptive_plot
n_df
```


## Two dim table - covid time VS each column 
```{r}
covid_time_table <- function(kpi){
  return(list(perc = round(ftable(covid_time, df[[kpi]]) / rowSums(ftable(covid_time, df[[kpi]])),3),
              n = table(covid_time, df[[kpi]])))}

# sapply(binari_exp, covid_time_table, simplify =FALSE)
# sapply(discrite_exp, covid_time_table, simplify =FALSE)
# sapply(categoric_exp, covid_time_table, simplify =FALSE)
# sapply(exploreatory_variables, covid_time_table, simplify =FALSE)
```


# Regression 

## Logistic regression
```{r}
# n1  = n_df[[1,'n']]
# n2  = n_df[[2,'n']]
# n3  = n_df[[3,'n']]
# n4  = n_df[[4,'n']]

mdl1 <- glm(is_atopic_first_year ~ SES_group + gender + type_of_pregnancy +
               mother_Atopic_diseases + father_Atopic_diseases +
              mother_year_birth + mother_education + number_of_children + covid_time  , data = df_mdl, family = "binomial")

mdl2 <- glm(is_atopic_second_year ~ SES_group + gender + 
             mother_Atopic_diseases + father_Atopic_diseases +
             mother_year_birth + mother_education + number_of_children + 
             type_of_pregnancy  + vaccine_12mo  + nursing_setup_at_12mo + covid_time , data=df_mdl, family='binomial')

mdl2_atopic <- glm(is_atopic_second_year ~ is_atopic_first_year + SES_group + gender + 
             mother_Atopic_diseases + father_Atopic_diseases +
             mother_year_birth + mother_education + number_of_children + 
             type_of_pregnancy  + vaccine_12mo  + nursing_setup_at_12mo + covid_time, data=df_mdl, family='binomial')

summary(mdl1)
# summary(mdl2)
# summary(mdl2_atopic)

confint(mdl1, level=0.9)
```



## GAM : 

```{r}
gam1 <- gam(is_atopic_first_year ~ SES_group + gender + type_of_pregnancy +
               mother_Atopic_diseases + father_Atopic_diseases +
               mother_year_birth + mother_education + number_of_children +
               s(DOB_count, bs='cr') ,data=df_mdl, family=binomial)

gam2 <- gam(is_atopic_second_year ~ SES_group + gender + 
             mother_Atopic_diseases + father_Atopic_diseases +
             mother_year_birth + mother_education + number_of_children + 
             type_of_pregnancy  + vaccine_12mo  + nursing_setup_at_12mo + s(DOB_count, bs='cr'), data=df_mdl, family=binomial)


gam2_atopic <- gam(is_atopic_second_year ~ is_atopic_first_year + SES_group + gender +
             mother_Atopic_diseases + father_Atopic_diseases +
             mother_year_birth + mother_education + number_of_children +
             type_of_pregnancy  + vaccine_12mo  + nursing_setup_at_12mo + s(DOB_count, bs='cr') ,data=df_mdl, family=binomial)


x <- summary(gam1)
summary(gam2)
# summary(gam2_atopic)
# plot.gam(gam2_atopic)

x$s.table
```

# Graphs
## first year 
```{r}
res_log1 = as.data.frame(summary(mdl1)$coefficients)
ci_1 = as.data.frame(confint.lm(mdl1, level = 0.9))
res_log1$lower_ci <- ci_1$`5 %`
res_log1$upper_ci <- ci_1$`95 %`
  
df_gam1 <- plot(getViz(gam1))$plots[[1]]$data$fit
df_gam1 <- df_gam1 %>% mutate(Born_at = if_else(x< g1, 'Up to March19', ifelse(x<g2, 'March19 - March20', ifelse(x<g3,'March20 - Feb21','From Feb21'))))
df_gam1$Born_at <- as.factor(df_gam1$Born_at)

df_gam1 <- df_gam1 %>%
  mutate(y_log = if_else(x < g1, 0, ifelse(x<g2, mdl1$coefficients['covid_time2'] ,
                                           ifelse(x<g3 ,mdl1$coefficients['covid_time3'],
                                                  mdl1$coefficients['covid_time4']))),

                  ci_lower = if_else(x < g1, 0,
                               ifelse(x<g2, res_log1['covid_time2', 'lower_ci'],
                                      ifelse(x<g3 , res_log1['covid_time3', 'lower_ci'],
                                             res_log1['covid_time4', 'lower_ci']))),
                  
                  ci_upper = if_else(x < g1, 0,
                               ifelse(x<g2, res_log1['covid_time2', 'upper_ci'],
                                      ifelse(x<g3 , res_log1['covid_time3', 'upper_ci'],
                                             res_log1['covid_time4', 'upper_ci']))))

#set dates 
plus = min(as.numeric(as.Date(df$DOB)))
df_gam1 <- df_gam1 %>% mutate(Date = as.Date(x + plus,  origin = '1970-01-01'))

# ## with Intercept:
# g1_interc = gam1$coefficients[1]
# l1_interc = mdl1$coefficients[1]
# 
# df_gam1$y <- df_gam1$y + g1_interc
# df_gam1$y_log <- df_gam1$y_log + l1_interc
# 
# plot1_first_year <- ggplot(df_gam1, aes(Date,y, fill = Born_at)) + 
#   geom_line(aes(col = Born_at), size = 1) +
#   geom_ribbon(aes(ymin = y - se*qnorm(0.975), ymax = y + se*qnorm(0.975), y=NULL), alpha = 0.1) +
#   
#   geom_line(aes(Date, y_log, col = Born_at), size = 1, linetype=2) + 
#   geom_ribbon(aes(ymin = y_log - se_log*qnorm(0.975), ymax = y_log + se_log*qnorm(0.975), y=NULL), alpha = 0.1)+
# 
#   scale_color_manual(values=viridis(5)) + scale_fill_manual(values=viridis(5)) + theme_bw() +
#   labs(title = "Birth date coefficient distribution", subtitle ="During the first year of a baby's life", x = 'Birth date', y = 'coefficient')+
#   geom_hline(yintercept = 0, linetype='dashed', alpha = 0.2) + 
#   scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")
# 
# # ggsave('full_first_year_mdl.jpeg',plot1_first_year, width =8, height =6)
# plot1_first_year

```

## Second year
```{r}
res_log2 = as.data.frame(summary(mdl2)$coefficients)
ci_2 = as.data.frame(confint.lm(mdl2, level = 0.9))
res_log2$lower_ci <- ci_2$`5 %`
res_log2$upper_ci <- ci_2$`95 %`


df_gam2 <- plot(getViz(gam2))$plots[[1]]$data$fit
df_gam2 <- df_gam2 %>% mutate(Born_at = if_else(x< g1, 'Up to March19', 
                                                ifelse(x<g2, 'March19 - March20', ifelse(x<g3,'March20 - Feb21','From Feb21'))))
df_gam2$Born_at <- as.factor(df_gam2$Born_at)

df_gam2 <- df_gam2 %>% mutate(y_log = if_else(x < g1, 0, 
                                ifelse(x<g2, mdl2$coefficients['covid_time2'] , 
                                       ifelse(x<g3 ,mdl2$coefficients['covid_time3'],
                                              mdl2$coefficients['covid_time4']))), 
         ci_lower = if_else(x < g1, 0, 
                               ifelse(x<g2, res_log2['covid_time2', 'lower_ci'] , 
                                      ifelse(x<g3 , res_log2['covid_time3', 'lower_ci'], 
                                             res_log2['covid_time4', 'lower_ci']))),
         
         ci_upper = if_else(x < g1, 0, 
                               ifelse(x<g2, res_log2['covid_time2', 'upper_ci'] , 
                                      ifelse(x<g3 , res_log2['covid_time3', 'upper_ci'], 
                                             res_log2['covid_time4', 'upper_ci'])))) 

#set dates
plus = min(as.numeric(as.Date(df$DOB)))
df_gam2 <- df_gam2 %>% mutate(Date = as.Date(x + plus,  origin = '1970-01-01'))
# 
# ## with Intercept:
# g2_interc = gam2$coefficients[1]
# l2_interc = mdl2$coefficients[1]
# 
# df_gam2$y <- df_gam2$y + g2_interc
# df_gam2$y_log <- df_gam2$y_log + l2_interc
# 
# plot2_second_year <- ggplot(df_gam2, aes(Date,y, fill = Born_at)) + 
#   geom_line(aes(col = Born_at), size = 1) +
#   geom_ribbon(aes(ymin = y - se*qnorm(0.975), ymax = y + se*qnorm(0.975), y=NULL), alpha = 0.1) +
# 
#   geom_line(aes(Date, y_log, col = Born_at), size = 1, linetype=2) + 
#   geom_ribbon(aes(ymin = y_log - se_log*qnorm(0.975), ymax = y_log + se_log*qnorm(0.975), y=NULL), alpha = 0.1)+
#   
#   scale_color_manual(values=viridis(5)) + scale_fill_manual(values=viridis(5)) + theme_bw() +
#   labs(title = "Birth date coefficient distribution", subtitle ="During the second year of a baby's life", x = 'Birth date', y = 'coefficient')+
#   geom_hline(yintercept = 0, linetype='dashed', alpha = 0.2)  + 
#   scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")
# 
# # ggsave('full_second_year_mdl.jpeg',plot2_second_year, width =8, height =6)
# plot2_second_year
```
## Only Log model 

```{r}
# Log plot first year 

# אולי כדאי לשנות את הויזואליזציה כדי שיהיה יותר ברור מה אנחנו רואים במודל של הרגרסיה הלוגיסטית 
log_plot1_first_year <- ggplot(df_gam1, aes(Date,y, fill = Born_at)) + 
  geom_line(aes(Date, y_log, col = Born_at), size = 1) + 
  geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper, y=NULL), alpha = 0.1)+

  scale_color_manual(values=viridis(5)) + scale_fill_manual(values=viridis(5)) + theme_bw() +
  labs(title = "Birth date group coefficient - Logistic model", subtitle ="During the first year of a baby's life", x = 'Birth date', y = 'Coefficient')+
  geom_hline(yintercept = 0, linetype='dashed', alpha = 0.2, size=1) + 
  scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")

log_plot1_first_year

# Log plot second year 

Log_plot2_second_year <- ggplot(df_gam2, aes(Date, y, fill = Born_at)) + 

  geom_line(aes(Date, y_log, col = Born_at), size = 1) + 
  geom_ribbon(aes(ymin = ci_lower, ymax = ci_upper, y=NULL), alpha = 0.1)+
  
  scale_color_manual(values=viridis(5)) + scale_fill_manual(values=viridis(5)) + theme_bw() +
  labs(title = "Birth date group coefficient - Logistic model", subtitle ="During the second year of a baby's life", x = 'Birth date', y = 'Coefficient')+
  geom_hline(yintercept = 0, linetype='dashed', alpha = 0.2, size=1)  + 
  scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")

Log_plot2_second_year

ggsave('Logistic_model_first_year.jpeg',log_plot1_first_year, width =8, height =6)
ggsave('Logistic_model_second_year.jpeg',Log_plot2_second_year, width =8, height =6)

```


## Only GAM model 
```{r}
# GAM plot fort year

GAM_plot1_first_year <- ggplot(df_gam1, aes(Date,y, fill = Born_at)) + 
  geom_line(aes(col = Born_at), size = 1) +
  geom_ribbon(aes(ymin = y - se*qnorm(0.975), ymax = y + se*qnorm(0.975), y=NULL), alpha = 0.1) +
  scale_color_manual(values=viridis(5)) + scale_fill_manual(values=viridis(5)) + theme_bw() +
  labs(title = "Birth date coefficient distribution - GAM model", subtitle ="During the first year of a baby's life", x = 'Birth date', y = 'coefficient')+
  geom_hline(yintercept = 0, linetype='dashed', alpha = 0.2) + 
  scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")

GAM_plot1_first_year

# GAM plot second year 
GAM_plot2_second_year <- ggplot(df_gam2, aes(Date,y, fill = Born_at)) + 
  geom_line(aes(col = Born_at), size = 1) +
  geom_ribbon(aes(ymin = y - se*qnorm(0.975), ymax = y + se*qnorm(0.975), y=NULL), alpha = 0.1) +

  scale_color_manual(values=viridis(5)) + scale_fill_manual(values=viridis(5)) + theme_bw() +
  labs(title = "Birth date coefficient distribution - GAM model", subtitle ="During the second year of a baby's life", x = 'Birth date', y = 'coefficient')+
  geom_hline(yintercept = 0, linetype='dashed', alpha = 0.2)  + 
  scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")

GAM_plot2_second_year

# ggsave('GAM_model_first_year.jpeg',GAM_plot1_first_year, width =8, height =6)
# ggsave('GAM_model_second_year.jpeg',GAM_plot2_second_year, width =8, height =6)
```

## Second year - atopic
```{r}
res_log2 = as.data.frame(summary(mdl2_atopic)$coefficients)

df_gam2 <- plot(getViz(gam2_atopic))$plots[[1]]$data$fit
df_gam2 <- df_gam2 %>% mutate(Born_at = if_else(x< g1, 'Up to March19', 
                                                ifelse(x<g2, 'March19 - March20', ifelse(x<g3,'March20 - Feb21','From Feb21'))))
df_gam2$Born_at <- as.factor(df_gam2$Born_at)

df_gam2 <- df_gam2 %>% mutate(y_log = if_else(x < g1, 0, 
                                ifelse(x<g2, mdl2_atopic$coefficients['covid_time2'] , 
                                       ifelse(x<g3 ,mdl2_atopic$coefficients['covid_time3'], mdl2_atopic$coefficients['covid_time4']))), 
         se_log = if_else(x < g1, res_log2['(Intercept)', 'Std. Error'], 
                               ifelse(x<g2, res_log2['covid_time2', 'Std. Error'] , 
                                      ifelse(x<g3 , res_log2['covid_time3', 'Std. Error'], 
                                             res_log2['covid_time4', 'Std. Error'])))) 

#set dates 
plus = min(as.numeric(as.Date(df$DOB)))
df_gam2 <- df_gam2 %>% mutate(Date = as.Date(x + plus,  origin = '1970-01-01'))

## with Intercept:
g2_interc = gam2_atopic$coefficients[1]
l2_interc = mdl2_atopic$coefficients[1]

df_gam2$y <- df_gam2$y + g2_interc
df_gam2$y_log <- df_gam2$y_log + l2_interc

plot2_second_year <- ggplot(df_gam2, aes(Date,y, fill = Born_at)) + 
  geom_line(aes(col = Born_at), size = 1) +
  geom_ribbon(aes(ymin = y - se*qnorm(0.975), ymax = y + se*qnorm(0.975), y=NULL), alpha = 0.1) +

  geom_line(aes(Date, y_log, col = Born_at), size = 1, linetype=2) + 
  geom_ribbon(aes(ymin = y_log - se_log*qnorm(0.975), ymax = y_log + se_log*qnorm(0.975), y=NULL), alpha = 0.1)+
  
  scale_color_manual(values=viridis(5)) + scale_fill_manual(values=viridis(5)) + theme_bw() +
  labs(title = "Birth date coefficient distribution", subtitle ="During the second year of a baby's life", x = 'Birth date', y = 'coefficient')+
  geom_hline(yintercept = 0, linetype='dashed', alpha = 0.2)  + 
  scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y")

# ggsave('second_year_mdl_with_atopic_first_year.jpeg',plot2_second_year, width =8, height =6)
plot2_second_year
```


# Predictions:
## Typical person :

```{r}
# Creating prediction of atopic disease for typical person  
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]}

n <- length(df_mdl$record_id) # number of rows in the data

# Data frame that contained the typical person n times in order to predict atopic diseas
typical_person <- data.frame(SES_group = rep(getmode(SES_group),n),
                             gender = rep(getmode(gender),n),
                             type_of_pregnancy = rep(getmode(type_of_pregnancy),n),
                             mother_Atopic_diseases = rep(getmode(mother_Atopic_diseases),n),
                             father_Atopic_diseases = rep(getmode(father_Atopic_diseases),n),
                             mother_year_birth = rep(mean(df_mdl$mother_year_birth),n),
                             mother_education = rep(getmode(mother_education),n),
                             number_of_children = rep(getmode(number_of_children),n),
                             nursing_setup_at_12mo = rep(getmode(nursing_setup_at_12mo),n),
                             vaccine_12mo = rep(getmode(vaccine_12mo),n),
                             is_atopic_first_year = rep(1,n))


# adding DOB for each observation
typical_person <- typical_person %>% mutate(DOB = df_mdl$DOB, DOB_count = df_mdl$DOB_count)
typical_person <- typical_person %>% mutate(Born_at = if_else(DOB_count< g1, 'Up to March19', ifelse(DOB_count<g2, 'March19 - March20', ifelse(DOB_count<g3,'March20 - Feb21','From Feb21'))), covid_time = if_else(DOB_count< g1, 1, ifelse(DOB_count<g2, 2, ifelse(DOB_count<g3,3,4))))
typical_person$covid_time <- as.factor(typical_person$covid_time)

typical_person_sick1 = typical_person

# predict
typical_person$gam_predict_first_year <- predict.gam(gam1, typical_person, type = 'response')
typical_person$gam_predict_second_year <- predict.gam(gam2, typical_person, type = 'response')
typical_person$gam_predict_second_year_sick1 <- predict.gam(gam2_atopic, typical_person_sick1, type = 'response')
typical_person$reg_predict_first_year <- predict(mdl1, typical_person, type = 'response')
typical_person$reg_predict_second_year <- predict(mdl2, typical_person, type = 'response')
typical_person$reg_predict_second_year_sick1 <- predict(mdl2_atopic, typical_person_sick1, type = 'response')

typical_person$gam_p_se1 <- predict.gam(gam1, typical_person, type = 'response', se.fit=TRUE)$se.fit
typical_person$gam_p_se2 <- predict.gam(gam2, typical_person, type = 'response', se.fit=TRUE)$se.fit
typical_person$gam_p_se2_sick1 <- predict.gam(gam2_atopic, typical_person_sick1, type = 'response', se.fit=TRUE)$se.fit
typical_person$reg_p_se1 <- predict(mdl1, typical_person, type = 'response', se.fit=TRUE)$se.fit
typical_person$reg_p_se2 <- predict(mdl2, typical_person, type = 'response', se.fit=TRUE)$se.fit
typical_person$reg_p_se2_sick1 <- predict(mdl2_atopic, typical_person_sick1, type = 'response', se.fit=TRUE)$se.fit


# Plot the predictions :
typical_baby_plot1 <- ggplot(typical_person, aes(DOB, gam_predict_first_year)) +  
                        geom_line(aes(col = Born_at), size = 1) +
                        geom_ribbon(aes(ymin = gam_predict_first_year - gam_p_se1*qnorm(0.975), ymax = gam_predict_first_year + gam_p_se1*qnorm(0.975), y = NULL, fill = Born_at), alpha=0.1)+ 
                        geom_line(aes(DOB, reg_predict_first_year, col = Born_at), size = 1, linetype=2) +
                        geom_ribbon(aes(ymin = reg_predict_first_year - reg_p_se1*qnorm(0.975), ymax = reg_predict_first_year + reg_p_se1*qnorm(0.975), y = NULL, fill = Born_at), alpha=0.1)+   
                        scale_color_manual(values=viridis(4)) + scale_fill_manual(values=viridis(4)) + theme_bw() +
                        labs(title = "Atopic disease risk", subtitle = "During the first year of a baby's life" , x = 'Birth date', y = 'Probability')  + 
                        scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y")


typical_baby_plot2 <- ggplot(typical_person, aes(DOB, gam_predict_second_year)) +
  geom_line(aes(col = Born_at), size = 1) +
  geom_ribbon(aes(ymin = gam_predict_second_year - gam_p_se2*qnorm(0.975), ymax = gam_predict_second_year + gam_p_se2*qnorm(0.975), y=NULL, fill=Born_at), alpha=0.1)+ 
  
  geom_line(aes(DOB, reg_predict_second_year, col = Born_at), size = 1, linetype=2) +
  geom_ribbon(aes(ymin = reg_predict_second_year - reg_p_se2*qnorm(0.975), ymax = reg_predict_second_year + reg_p_se2*qnorm(0.975), y = NULL, fill = Born_at), alpha=0.1)+   
  scale_color_manual(values=viridis(4)) + scale_fill_manual(values=viridis(4)) + theme_bw() +
labs(title = "Atopic disease risk", subtitle = "During the second year of a baby's life" , x = 'Birth date', y = 'Probability')   + 
  scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y")

# ggsave('typical_baby1.jpeg',typical_baby_plot1, width =8, height =6)
# ggsave('typical_baby2.jpeg',typical_baby_plot2, width =8, height =6)

typical_baby_plot1
typical_baby_plot2
```

```{r}
# separeted graphs of prob :

prob_first_year_log <- ggplot(typical_person, aes(DOB, gam_predict_first_year)) +  
                        geom_line(aes(DOB, reg_predict_first_year, col = Born_at), size = 1) +
                        geom_ribbon(aes(ymin = reg_predict_first_year - reg_p_se1*qnorm(0.975), ymax = reg_predict_first_year + reg_p_se1*qnorm(0.975), y = NULL, fill = Born_at), alpha=0.1)+   
                        scale_color_manual(values=viridis(4)) + scale_fill_manual(values=viridis(4)) + theme_bw() +
                        labs(title = "Atopic disease risk - Logistic model", subtitle = "During the first year of a baby's life - Logistic model" , x = 'Birth date', y = 'Probability')  + 
                        scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")
prob_first_year_log



prob_first_year_GAM <- ggplot(typical_person, aes(DOB, gam_predict_first_year)) +  
                        geom_line(aes(col = Born_at), size = 1) +
                        geom_ribbon(aes(ymin = gam_predict_first_year - gam_p_se1*qnorm(0.975), ymax = gam_predict_first_year + gam_p_se1*qnorm(0.975), y = NULL, fill = Born_at), alpha=0.1)+ 
                        scale_color_manual(values=viridis(4)) + scale_fill_manual(values=viridis(4)) + theme_bw() +
                        labs(title = "Atopic disease risk - GAM model", subtitle = "During the first year of a baby's life" , x = 'Birth date', y = 'Probability')  + 
                        scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")
prob_first_year_GAM

prob_second_year_log <- ggplot(typical_person, aes(DOB, gam_predict_second_year)) +
  geom_line(aes(DOB, reg_predict_second_year, col = Born_at), size = 1) +
  geom_ribbon(aes(ymin = reg_predict_second_year - reg_p_se2*qnorm(0.975), ymax = reg_predict_second_year + reg_p_se2*qnorm(0.975), y = NULL, fill = Born_at), alpha=0.1)+   
  scale_color_manual(values=viridis(4)) + scale_fill_manual(values=viridis(4)) + theme_bw() +
labs(title = "Atopic disease risk - Logistic model", subtitle = "During the second year of a baby's life" , x = 'Birth date', y = 'Probability')   + 
  scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")
prob_second_year_log

prob_second_year_GAM <- ggplot(typical_person, aes(DOB, gam_predict_second_year)) +
  geom_line(aes(col = Born_at), size = 1) +
  geom_ribbon(aes(ymin = gam_predict_second_year - gam_p_se2*qnorm(0.975), ymax = gam_predict_second_year + gam_p_se2*qnorm(0.975), y=NULL, fill=Born_at), alpha=0.1)+ 
  scale_color_manual(values=viridis(4)) + scale_fill_manual(values=viridis(4)) + theme_bw() +
labs(title = "Atopic disease risk - GAM model", subtitle = "During the second year of a baby's life" , x = 'Birth date', y = 'Probability')   + 
  scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + theme(legend.position = "none")
prob_second_year_GAM

# 
# ggsave('probabilty_Log_model_plot_first_year.jpeg',prob_first_year_log, width =8, height =6)
# ggsave('probabilty_GAM_model_plot_first_year.jpeg',prob_first_year_GAM, width =8, height =6)
# ggsave('probabilty_Log_model_plot_second_year.jpeg',prob_second_year_log, width =8, height =6)
# ggsave('probabilty_GAM_model_plot_second_year.jpeg',prob_second_year_GAM, width =8, height =6)
```




```{r}

comp <- data.frame('DOB' = typical_person$DOB, 'Born_at' = typical_person$Born_at,  
                   'gam_predict_second_year' = typical_person$gam_predict_second_year, 
                   'gam_predict_second_year_sick1' = typical_person$gam_predict_second_year_sick1,
                   'reg_predict_second_year' = typical_person$reg_predict_second_year,
                   'reg_predict_second_year_sick1' = typical_person$reg_predict_second_year_sick1)

com_plot <- ggplot(comp) +
  geom_line(aes(x = DOB, y = gam_predict_second_year, col = Born_at), size = 1) +
  geom_line(aes(x = DOB, y = gam_predict_second_year_sick1, col = Born_at), size = 1) +
  
  geom_line(aes(x=DOB, y=reg_predict_second_year, col = Born_at), size = 1, linetype=2) +
  geom_line(aes(x=DOB, y=reg_predict_second_year_sick1, col = Born_at), size = 1, linetype=2) + 
  
  geom_text(aes(x = max(DOB), y = max(gam_predict_second_year), label = "X"), vjust = -1, hjust = -0.5) +
  geom_text(aes(x = max(DOB), y = max(gam_predict_second_year_sick1), label = "V"), vjust = -1, hjust = -0.5) +
  
  labs(title = "Compare Atopic disease risk in the second year", subtitle = "With and without atopic disease as variable in the model (Healthy baby in the first year)" , x = 'Birth date', y = 'Probability') + 
  scale_color_manual(values=viridis(4)) + scale_fill_manual(values=viridis(4)) + theme_bw() +
  scale_x_date(date_breaks = "4 months", date_labels = "%b\n%y") + ylim(c(0.2,0.8))

comp <- comp %>% mutate(gam_diff = gam_predict_second_year_sick1 - gam_predict_second_year, 
                        log_diff = reg_predict_second_year_sick1 - reg_predict_second_year)  
comp %>% group_by(Born_at) %>% summarise(round(100*mean(gam_diff)), round(100*mean(log_diff)))

# ggsave('com_plot_of_gam2.jpeg',com_plot, width =10, height =6)

```


