```{r, echo=F, message=F}
# libraries:
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(reshape)
options(scipen=5, digits = 5)
```

# Descriptive statistics

```{r}
# Reading the file:
# dir <- "C:/Users/Merav/Documents/GitHub/Statistics-Project/atopic_comorbidities_first_second_year_3.1.23.xlsx"
dir <- "C:/Users/edena/Documents/GitHub/Statistics-Project/atopic_comorbidities_first_second_year_3.1.23.xlsx"
#dir<-"C:/Users/Shahar/Documents/GitHub/Statistics-Project/atopic_comorbidities_first_second_year_3.1.23.xlsx"
    
df <- read_excel(dir, sheet = 1)
df <- df %>% mutate(DOB = as.Date(DOB)) 

# Arranging df:
# Filtering only participants that completed the survey:
df <- df %>% filter(is.na(lost_of_followup))
# Filtering only participants that completed the second year:
df <- df %>% filter(month_survey_complete == 2)

# Removing non relevant columns: from type_of_allergy to 12_month_FA_type_allergy
#remove_columns = colnames(df)[51:88]
df <- df[,-c(51:88)]

# Removing columns with allot on NA:
not_relevant <- c('allergist_followup', 'last_spt', 'epipen', 'mistake_exposure', 'reaction_type24', 'diagnosis_by', 'lost_of_followup',"mother_no_comorbidities","mother_other","father_no_comorbidities","father_other","sibling1_other","sibling1_no_comorbidities","sibling2_other","sibling2_no_comorbidities","sibling3_other","sibling3_no_comorbidities","sibling4_other","sibling4_no_comorbidities")
df <- df[-which(colnames(df) %in% not_relevant)]

# Adding binary columns 
# A. Did any one from family (mother, father, sib) have *any* of the disease?
df$family_Atopic_diseases_sum <- rowSums(df[,14:37])

# B. Did somebody from family have a specific disease?
# NEED TO FILL IN

# C. Did a disease appear in a specific family member?
df$mother_Atopic_diseases_sum <- rowSums(df[,14:17])
df$father_Atopic_diseases_sum <- rowSums(df[,18:21])
df$sibling_Atopic_diseases_sum <- rowSums(df[,22:37])

df <- df %>% mutate(family_Atopic_diseases = ifelse(family_Atopic_diseases_sum >0,1,0),
                    mother_Atopic_diseases = ifelse(mother_Atopic_diseases_sum>0,1,0),
                    father_Atopic_diseases = ifelse(father_Atopic_diseases_sum > 0, 1,0),
                    sibling_Atopic_diseases = ifelse(sibling_Atopic_diseases_sum > 0 ,1, 0))

# Changing to binary variables:
df$gender[df$gender == 2] <- 0
df$`Jew/Arab`[df$`Jew/Arab` == 2] <- 0
df$food_allergy_24_month[df$food_allergy_24_month == 2] <- 0
df$inhalation_24_month[df$inhalation_24_month == 2] <- 0
df$prevention_therapy[df$prevention_therapy == 2] <- 0
df$AD_24_month[df$AD_24_month == 2] <- 0
df$steroids_treatment24[df$steroids_treatment24 == 2] <- 0
df$ABX_treatment_24_months[df$ABX_treatment_24_months == 2] <- 0
df$hospitalization_24_months[df$hospitalization_24_months == 2] <- 0
df$chronic_disease_24[df$chronic_disease_24 == 2] <- 0

#Changing NA to 0 for 
df$number_ABX_treatment_24_months<- replace(df$number_ABX_treatment_24_months, is.na(df$number_ABX_treatment_24_months), 0)
df$hospitalization_24_months<- replace(df$hospitalization_24_months, is.na(df$hospitalization_24_months), 0)

df$prevention_therapy<- replace(df$prevention_therapy, is.na(df$prevention_therapy), 0)
df$number_inhalation<- replace(df$number_inhalation, is.na(df$number_inhalation), 0)

df$AD_treatment_24_month<- replace(df$AD_treatment_24_month, is.na(df$AD_treatment_24_month), 0)
df$steroids_treatment24<- replace(df$steroids_treatment24, is.na(df$steroids_treatment24), 0)
df$number_steroid_treat<- replace(df$number_steroid_treat
, is.na(df$number_steroid_treat), 0)

df$number_of_ABX_first_year<- replace(df$number_of_ABX_first_year, is.na(df$number_of_ABX_first_year), 0)
```


```{r}
#Creating dependent variables:
#option A of explanatory var:
df <- df %>% mutate(is_atopic_first_year = ifelse((AD_first_year + FA_first_year + ABX_fisrt_year)>0,1,0), is_atopic_second_year = ifelse((food_allergy_24_month + inhalation_24_month + AD_24_month)>0,1,0))
#option B of explanatory var:
#From mail
```

```{r}
#Choosing explanatory variables: Ones that have a sufficient number of observation before and after Corona
#The distribution of observations according to the timeline of the corona. Before the corona = 1, the first six months of the corona = 2  and after = 3:

group1 <- as.Date("2019-03-01")
group2 <- as.Date("2020-03-11")
group3 <- as.Date("2021-02-07")
df <- df %>% mutate(covid_time = ifelse(DOB < group1, 1, ifelse(DOB < group2, 2, ifelse(DOB<group3, 3, 4))))
table(df$covid_time)

# at this moment there is no sutible data from group 4 - post corona 

# mean(df[which(df$covid_time == 1),]$is_atopic_second_year, na.rm = T)
# mean(df[which(df$covid_time == 2),]$is_atopic_second_year, na.rm = T)
# mean(df[which(df$covid_time == 3),]$is_atopic_second_year, na.rm = T)

```
# Summary of the data:

```{r}
# Taking a first view at data: 
summary(df)
glimpse(df)
# attach(df)

# One strange observation- gave birth at 12??
df[which(df$mother_year_birth> 2000),] # to take off ?? 
```

```{r}
attach(df) ##מה זה? -- יוצר משתנה עבור כל עמודה בפנה עצמה בלי קשר לדאטה

# Show the distribution of some variables
hist(mother_year_birth)
hist(SES) #socio-economic status
```

```{r}
# Frequency table for each column
tablelist <- mapply(table, df)
#tablelist
```

```{r}
# How many NA are in each column
NA_count <- as.data.frame(t(df %>% summarise_all(funs(sum(is.na(.)))))) %>% dplyr::rename("amount of NA" = 1) 
NA_count <- NA_count %>% mutate(Name = rownames(NA_count))
NA_column = NA_count %>% filter(`amount of NA` >0) %>% arrange(`amount of NA`)
```
# two dimention tables:
```{r}
#For each explanatory variable:
print("SES")
table(df$covid_time,df$SES)
print("gender")
table(df$covid_time,df$gender)
print("mother_education")
table(df$covid_time,df$mother_education)
print("preganancy_number")
table(df$covid_time,df$preganancy_number)
print("type_of_pregnancy")
table(df$covid_time,df$type_of_pregnancy)
print("mode of delivery")
table(df$covid_time,df$`mode of delivery`)
print("mother_Atopic_diseases")
table(df$covid_time,df$mother_Atopic_diseases)
print("father_Atopic_diseases")
table(df$covid_time,df$father_Atopic_diseases)
print("sibling_Atopic_diseases")
table(df$covid_time,df$sibling_Atopic_diseases)
print("vaccine_12mo")
table(df$covid_time,df$vaccine_12mo)
print("nursing_setup_at_12mo")
table(df$covid_time,df$nursing_setup_at_12mo)
print("daycare_24month")
table(df$covid_time,df$daycare_24month)
print("vaccines_24month")
table(df$covid_time,df$vaccines_24month)
```

```{r}
#For each dependent variable: First year
print("HRAD_first_year")
table(df$covid_time,df$HRAD_first_year)
print("AD_first_year")
table(df$covid_time,df$AD_first_year)
print("FA_first_year")
table(df$covid_time,df$FA_first_year)
print("ABX_fisrt_year")
table(df$covid_time,df$ABX_fisrt_year)
print("is_atopic_first_year")
table(df$covid_time,df$is_atopic_first_year)
```

```{r}
table(df$mother_year_birth,df$is_atopic_first_year)

table(df$mother_year_birth,df$is_atopic_first_year)

```


```{r}
#For each dependent variable: Second year
print("food_allergy_24_month")
table(df$covid_time,df$food_allergy_24_month)
print("inhalation_24_month")
table(df$covid_time,df$inhalation_24_month)
print("AD_24_month")
table(df$covid_time,df$AD_24_month)
print("chronic_rhinitis_24_month")
table(df$covid_time,df$chronic_rhinitis_24_month)
print("hospitalization_24_months")
table(df$covid_time,df$hospitalization_24_months)
print("chronic_disease_24")
table(df$covid_time,df$chronic_disease_24)
print("AD_24_month")
table(df$covid_time,df$AD_24_month)
print("chronic_rhinitis_24_month")
table(df$covid_time,df$chronic_rhinitis_24_month)
print("is_atopic_second_year")
table(df$covid_time,df$is_atopic_second_year)

```

remove NA:
```{r}
df <- df %>% drop_na(AD_first_year, FA_first_year, ABX_fisrt_year,food_allergy_24_month, inhalation_24_month, AD_24_month) 
```

plots for presentation:
```{r,fig.width=10}

plot_df_1 <- df %>% select(covid_time, AD_first_year, AD_24_month, FA_first_year,food_allergy_24_month, ABX_fisrt_year,inhalation_24_month) %>% group_by(covid_time) %>% summarise(AD_first_year = sum(AD_first_year), AD_24_month = sum(AD_24_month), FA_first_year = sum(FA_first_year),food_allergy_24_month = sum(food_allergy_24_month), ABX_fisrt_year = sum(ABX_fisrt_year),inhalation_24_month = sum(inhalation_24_month)) %>% gather(chronic_disease, count, AD_first_year:inhalation_24_month, factor_key=TRUE)

plot_df_2 <- df %>% select(covid_time,is_atopic_first_year,is_atopic_second_year) %>% group_by(covid_time) %>% summarise(is_atopic_first_year= sum(is_atopic_first_year), is_atopic_second_year= sum(is_atopic_second_year)) %>% gather(chronic_disease, count, is_atopic_first_year:is_atopic_second_year, factor_key=TRUE)

ggplot(plot_df_1,aes(x=chronic_disease, y= count, fill = as.factor(covid_time))) +
    geom_col() + xlab("Chronic Disease") + ylab("Cases") +
  scale_fill_manual(values=c('dodgerblue4', 'darkorange1', 'green4'),name = "Group")

ggplot(plot_df_2,aes(x=chronic_disease, y= count, fill = as.factor(covid_time))) +
    geom_col(position = "dodge") + scale_fill_discrete(name = "Group")+ xlab("Chronic Disease") + ylab("Cases") +
  scale_fill_manual(values=c('dodgerblue4', 'darkorange1', 'green4'))

table(covid_time)
```

```{r}
explanatory_variables <- df %>% select(mother_year_birth,SES, Jew/Arab,DOB, gender, mother_education, number_of_children, preganancy_number,type_of_pregnancy,Allergy_total,mother_asthma,mother_atopic_dermatitis,mother_Allergic_rhinitis,mother_food_allergy,father_asthma,father_atopic_dermatitis,father_Allergic_rhinitis,father_food_allergy,sibling1_asthma,sibling1_atopic_dermatitis,sibling1_Allergic_rhinitis,sibling1_food_allergy,sibling2_asthma,sibling2_atopic_dermatitis,sibling2_Allergic_rhinitis,sibling2_food_allergy,sibling3_asthma,sibling3_atopic_dermatitis,sibling3_Allergic_rhinitis,sibling3_food_allergy,sibling4_asthma,sibling4_atopic_dermatitis,sibling4_Allergic_rhinitis,sibling4_food_allergy,HRAD_first_year,AD_first_year,FA_first_year,ABX_fisrt_year, number_of_ABX_first_year,vaccine_12mo,nursing_setup_at_12mo,daycare_24month,vaccines_24month,food_allergy_24_month,inhalation_24_month,number_inhalation,prevention_therapy,AD_24_month,AD_treatment_24_month,steroids_treatment24,number_steroid_treat,chronic_rhinitis_24_month,ABX_treatment_24_months,number_ABX_treatment_24_months,hospitalization_24_months,chronic_disease_24,month_survey_complete,family_Atopic_diseases_sum,mother_Atopic_diseases_sum,father_Atopic_diseases_sum,sibling_Atopic_diseases_sum, family_Atopic_diseases,mother_Atopic_diseases,father_Atopic_diseases,sibling_Atopic_diseases,is_atopic_first_year,is_atopic_second_year,covid_time)
df
colnames(df)
```








# Regressions

```{r}
# Run some logistic regression on some variables:

# # split the data into train and test 
# set.seed(1)
# sample <- sample(c(TRUE, FALSE), nrow(df), replace=TRUE, prob=c(0.7,0.3))
# train <- df[sample, ]
# test <- df[!sample, ]  

# Finding the most relevant variables to use in the model 
intresting_col <- df %>% select(SES, `Jew/Arab`, gender, `Study group (MARCH 2020)`, study_group_COMEET, mother_education, number_of_children, preganancy_number, type_of_pregnancy, `mode of delivery`, `type of allergy`, Milk, Egg, Soy, Peanuts, Sesame, Almonds, `Tree nuts`, `Other food`, `12_month_number_of_inhalations`, `12_month_FA_type_allergy`, HRAD_first_year, AD_first_year, FA_first_year, ABX_fisrt_year, number_of_ABX_first_year, vaccine_12mo, nursing_setup_at_12mo, daycare_24month, vaccines_24month, food_allergy_24_month, inhalation_24_month, number_inhalation, prevention_therapy, AD_24_month, AD_treatment_24_month, steroids_treatment24, number_steroid_treat, chronic_rhinitis_24_month, number_ABX_treatment_24_months, hospitalization_24_months, chronic_disease_24, month_survey_complete, family_Atopic_diseases, mother_Atopic_diseases, father_Atopic_diseases, sibling_Atopic_diseases)

cor_df <- as.data.frame(cor(as.matrix.noquote(intresting_col), use = "pairwise.complete.obs"))

# model of inhalation requirement with the relevant fields 
mdl <- glm(`type of allergy`~ ., data = intresting_col)
summary(mdl)
```

```{r}
cor(intresting_col, use="complete.obs")
```




```{r}
ggplot(gather(intresting_col[,1:12]) %>% na.omit() , aes(value)) + 
    geom_histogram(bins = 10) + 
    facet_wrap(~key, scales = 'free_x')

ggplot(gather(intresting_col[,13:24]) %>% na.omit() , aes(value)) + 
    geom_histogram(bins = 10) + 
    facet_wrap(~key, scales = 'free_x')

ggplot(gather(intresting_col[,25:36]) %>% na.omit() , aes(value)) + 
    geom_histogram(bins = 10) + 
    facet_wrap(~key, scales = 'free_x')

ggplot(gather(intresting_col[,37:47]) %>% na.omit() , aes(value)) + 
    geom_histogram(bins = 10) + 
    facet_wrap(~key, scales = 'free_x')
```
